from enum import Enum


class PipelineStatus(Enum):
    PENDING = "PENDING"
    FAILED = "FAILED"
    IDLE = "IDLE"
    INPUT_FETCHED = "INPUT_FETCHED"
    PROCESSING_STARTED = "PROCESSING_STARTED"
    PROCESSING_COMPLETED = "PROCESSING_COMPLETED"
    OUTPUT_UPDATED = "OUTPUT_UPDATED"
    ERROR = "ERROR"
    STOPPED = "STOPPED"