server: {
  "ip": "0.0.0.0",
  "port": 12345,
  "debug": True,
  "ssl": False,
  "ssl_key": "",
  "ssl_cert": ""
}
database: {
  "uri": 'sqlite:///hire.db',
   "track_modifications": false
}
email: {
  "from": "",
  "username": "",
  "password": "",
  "smtp_host": "smtp.gmail.com",
  "smtp_port": 465
}
jwt: {
    "secret_key": 'secret_key'
}
