server: {
  "ip": "0.0.0.0",
  "port": 12345,
  "debug": True,
  "ssl": False,
  "ssl_key": "",
  "ssl_cert": ""
}

database: {
  "uri": 'sqlite:///hire.db',
   "track_modifications": false
}

email: {
  "from": "hire",
  "username": "info.garret.events@gmail.com",
  "password": "ekdp awmj tkgb shoo",
  "smtp_host": "smtp.gmail.com",
  "smtp_port": 465,
  "imap_host": "imap.gmail.com",
  "imap_port": 993,
}

jwt: {
    "secret_key": 'secret_key'
}

assets: {
    "resume": "./src/Static/Resume/Documents",
    "json_resume": "./src/Static/Resume/Json",
}

profiler: {
  "github_token": "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",
  "google_api_key": "4b2bd8d449f606e0f71f57875c46bbe14fd93def",
  "rapid_api_key": "8db03861bbmsh22f75dbc69e476dp12c8f1jsn7aff481e6529",
  "google_search_url": "",
  "batch_size": 5,
  "intervals": {
    linkedin_scraping: 1,
    text_extraction: 1,
    github_scraping: 1,
    google_scraping: 1,
    profile_creation: 1
  },
  "scoring": {
    "weights": {
      "technical": 0.4,
      "experience": 0.35,
      "github": 0.25
    },
    "min_passing_score": 70.0
  }
}

llm: {
   "genai_token" : "AIzaSyDHrYRfS6X6e1Ia1OwmMoRw48JD94tp28o",
   "poppler_path" : "C:\\Program Files\\poppler-24.08.0\\Library\\bin" # make sure its in backslash
}

watcher: {
  "watcher_folder": "./src/PipeLines/Integration/FileWatcher/Watcher/watcher_folder",
  "failed_folder": "./src/PipeLines/Integration/FileWatcher/Watcher/failed_folder",
  "check_interval": 1
}

email_pipe_line: {
  batch_size: 10,
  check_interval: 1,
  folder: "INBOX",
  allowed_attachments: [
    ".pdf",
    ".doc",
    ".docx"
  ]
}