
server:
  ip: "0.0.0.0"
  port: 5000
  debug: true
  ssl: false

database:
  uri: "sqlite:///hire.db"
  track_modifications: false

email:
  from: "hire"
  username: ""  # Add through secrets
  password: ""  # Add through secrets
  smtp_host: "smtp.gmail.com"
  smtp_port: 465
  imap_host: "imap.gmail.com" 
  imap_port: 993

jwt:
  secret_key: "your_jwt_secret_key_here"  # Change this in production

assets:
  resume: "./src/Static/Resume/Documents"
  json_resume: "./src/Static/Resume/Json"

profiler:
  github_token: ""  # Add through secrets
  google_api_key: ""  # Add through secrets
  rapid_api_key: ""  # Add through secrets
  batch_size: 5
  intervals:
    linkedin_scraping: 1
    text_extraction: 1
    github_scraping: 1
    google_scraping: 1
    profile_creation: 1
  scoring:
    weights:
      technical: 0.4
      experience: 0.35
      github: 0.25
    min_passing_score: 70.0

llm:
  genai_token: ""  # Add through secrets
  poppler_path: "/usr/bin"

watcher:
  watcher_folder: "./src/PipeLines/Integration/FileWatcher/Watcher/watcher_folder"
  failed_folder: "./src/PipeLines/Integration/FileWatcher/Watcher/failed_folder"
  check_interval: 1

email_pipe_line:
  batch_size: 10
  check_interval: 1
  folder: "INBOX"
  allowed_attachments:
    - ".pdf"
    - ".doc"
    - ".docx"
